# Generated by Django 5.0.6 on 2024-07-04 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='acitve',
            new_name='active',
        ),
    ]
